Add welcome template for Kansas, USA
osmbe/osm-welcome-belgium pull request #127
Opened 2021-11-02 02:06 UTC by ZeLonewolf

Kansas is an undermapped state in the USA, and we would like to help build a community there by welcoming new users.  I think I've added the right pieces here except the osmcha filter ID, which I'm not sure how to populate.

2021-11-02 02:11 UTC, 1ec5 commented on templates/messages/kansas/en/default.md
> +If you have any questions at all, we can help out: you think you might have broken something, you’re in doubt how to map something particular, or you just want to know more about OpenStreetMap, conta
```suggestion
If you have any questions at all, we can help out: if you think you might have broken something, are in doubt how to map something particular, or just want to know more about OpenStreetMap, contact us!
```

2021-11-02 09:19 UTC, jbelien commented
Awesome, thanks @ZeLonewolf and @1ec5 !

I'll take care of this right now.

2021-11-02 09:24 UTC, jbelien requested changes
Your `kansas.geojson` file is not correct:
- The file is invalid (one of the latitude is `40.`)
- We need a Polygon and you provided a LineString

Please use <http://polygons.openstreetmap.fr/> to provide a valid Polygon.
Thanks!

2021-11-03 02:13 UTC, ZeLonewolf commented
Should be all set - thanks!

2021-11-03 19:29 UTC, jbelien approved these changes

2021-11-03 19:32 UTC, merged

2021-11-03 19:50 UTC, jbelien commented
Deployed: https://welcome.osm.be/kansas/list 🚀

2021-11-03 19:53 UTC, ZeLonewolf commented
Yay, thanks for your help!