Update regions.yaml
osmbe/osm-welcome-belgium pull request #671
Opened 2022-08-19 02:58 UTC by ikopanji

2022-08-19 05:48 UTC, jbelien requested changes
Hello @ikopanji ,

Don't forget to add the GeoJSON file of your region!
Check https://github.com/osmbe/osm-welcome-tool/blob/2.x/CONTRIBUTING.md#add-a-new-region

2022-08-19 05:48 UTC, jbelien commented on config/regions.yaml
> +    flag: id
Must be an emoji!

```suggestion
    flag: 🇮🇩
```

2022-08-19 08:31 UTC, ikopanji commented on config/regions.yaml
> +    flag: id
Dear @jbelien,
I've already uploaded the area for Indonesia and updated the code to "ID" in accordance with your suggestion.

2022-08-19 08:48 UTC, jbelien commented on config/regions.yaml
> +    flag: id
I've merge #672 into this PR and cleaned your GeoJSON file.

⚠️ The `flag` property MUST be an emoji (not a text, not `id`, not `ID`)! See my suggested change!

2022-08-19 10:00 UTC, ikopanji commented on config/regions.yaml
> +    flag: id
Oops, already fixed.

2022-08-20 09:51 UTC, jbelien approved these changes

2022-08-20 09:51 UTC, merged

2022-08-20 10:01 UTC, jbelien commented
🚀 Deployed: https://welcome.osm.be/indonesia/list
(process is running)